### ISSUE TITLE
How to change the Background Pic?

### ISSUE THREAD

**Issue by czhaocs** [umehina/kibou_lite#2]
**How to change the Background Pic?**
**请问怎样更改背景图？**
**どのように背景図変更しますか？**

**Comment by umehina** [comment]
[css/style.css](https://github.com/metheno/kibou_lite/blob/master/css/style.css) 第 [313](https://github.com/metheno/kibou_lite/blob/7256f5447680d66f193539870dcbeddc3e75a53d/css/style.css#L313) 行

**Comment by czhaocs** [comment]
thanks




发自网易邮箱大师
On 10/15/2017 20:18, metheno wrote:

Closed #2.
